### ISSUE TITLE
README

### ISSUE THREAD

**Issue by matthewdking** [FACN3/Boltware#10]
## Your readme is the first page anyone will see when they come to your repository, make it look awesome :tada: :sparkles: 

Things to consider adding:
+ user stories
+ link to the website #11 
+ what you plan to do next (stretch goals)
+ how you plan to split up the work

The readme is written in markdown and I find [this cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) really helpful for styling and if you want to have some fun then add some [emojis](https://www.webpagefx.com/tools/emoji-cheat-sheet/).

**Comment by haithhawk** [comment]
I just edited and added what Matt mentioned

**Comment by matthewdking** [comment]
@haithhawk I am reopening this because I opened the issue I should be the one to close it once I have seen you have made the changes :innocent:

**Comment by matthewdking** [comment]
If you are making changes then commit referencing this issue by writing relates #10. This way I can see that you have actually made these changes as it will appear in this issue so I can see it and close the issue :smile:

**Comment by haithhawk** [comment]
I just did , thanks Matt
