### ISSUE TITLE
Image in top left

### ISSUE THREAD

**Issue by KatiaAsh** [FACN3/Boltware#31]
You guys already have a home button on navbar why you need this image for home? :thinking: :thought_balloon: 
![screenshot from 2017-11-02 10-27-24](https://user-images.githubusercontent.com/26391874/32317136-71762e8a-bfbb-11e7-93ef-4f41f9e516c0.png)

**Comment by MarlenAw** [comment]
@KatiaAsh 
This image is our Logo lol..for some reason its not showing on the website :confused:

**Comment by KatiaAsh** [comment]
@MarlenAw I saw the last update and logo look amazing (Love it :sparkling_heart: )
I'm gonna close this issue :+1:
