### ISSUE TITLE
Form message black font

### ISSUE THREAD

**Issue by Amirk390** [FACN3/Boltware#38]
https://github.com/MarlenAw/Boltware/blob/master/index.html#L112

The text that is written down in the black background form boxs is black as well,

i think it would be a good idea to maybe change it to a different color :smirk:

![image](https://user-images.githubusercontent.com/24490876/32317793-abf1ff60-bfbd-11e7-8a34-0909c1d81cf6.png)

**Comment by MarlenAw** [comment]
Working on it
